--1
SELECT DISTINCT CLASSES.COUNTRY
FROM CLASSES
WHERE CLASSES.NUMGUNS>=ALL(SELECT MAX(CLASSES.NUMGUNS) FROM CLASSES)

--2
SELECT CLASSES.CLASS
FROM CLASSES
WHERE CLASSES.CLASS IN (SELECT SHIPS.CLASS FROM SHIPS WHERE SHIPS.NAME IN (SELECT OUTCOMES.SHIP FROM OUTCOMES WHERE OUTCOMES.RESULT='sunk'))

--3
SELECT SHIPS.NAME
FROM SHIPS
WHERE SHIPS.CLASS IN (SELECT CLASSES.CLASS FROM CLASSES WHERE CLASSES.BORE=16)

--4
SELECT BATTLES.NAME
FROM BATTLES, OUTCOMES
WHERE OUTCOMES.BATTLE=BATTLES.NAME AND OUTCOMES.SHIP IN (SELECT SHIPS.NAME FROM SHIPS WHERE SHIPS.CLASS='Kongo');

--5
SELECT s.CLASS, s.NAME
FROM SHIPS s, CLASSES c
WHERE s.CLASS=c.CLASS AND c.NUMGUNS>=ALL(SELECT CLASSES.NUMGUNS FROM CLASSES WHERE CLASSES.BORE=c.BORE)
ORDER BY s.CLASS;