--1
SELECT MOVIE.TITLE, MOVIE.[YEAR], MOVIE.LENGTH
FROM MOVIE
WHERE (MOVIE.LENGTH > 120 OR MOVIE.LENGTH IS NULL) AND MOVIE.[YEAR] < 2000;

--2
SELECT MOVIESTAR.NAME, MOVIESTAR.GENDER
FROM MOVIESTAR
WHERE MOVIESTAR.NAME LIKE 'J%' AND MOVIESTAR.BIRTHDATE>1948
ORDER BY MOVIESTAR.NAME DESC;

--3
SELECT STUDIO.NAME, COUNT(MOVIE.TITLE)
FROM STUDIO, MOVIE
WHERE MOVIE.STUDIONAME=STUDIO.NAME
GROUP BY STUDIO.NAME;

--4
SELECT STARSIN.STARNAME, COUNT(*)
FROM STARSIN, MOVIE
WHERE STARSIN.MOVIETITLE = MOVIE.TITLE
GROUP BY STARSIN.STARNAME;


--5
SELECT MOVIE.STUDIONAME, MOVIE.TITLE, MOVIE.[YEAR]
FROM MOVIE, STUDIO
WHERE MOVIE.[YEAR]=
(SELECT MAX(MOVIE.[YEAR]) 
FROM MOVIE 
WHERE MOVIE.STUDIONAME=STUDIO.NAME)
GROUP BY MOVIE.STUDIONAME, MOVIE.TITLE, MOVIE.YEAR;


--6
SELECT MOVIESTAR.NAME
FROM MOVIESTAR
WHERE MOVIESTAR.BIRTHDATE=(SELECT MAX(MOVIESTAR.BIRTHDATE) FROM MOVIESTAR WHERE MOVIESTAR.GENDER='M');

-- 7 option 1
SELECT m.STUDIONAME, s.STARNAME, COUNT(s.STARNAME) AS NUM_MOVIES
FROM MOVIE m, STARSIN s
WHERE m.TITLE=s.MOVIETITLE AND m.[YEAR]=s.MOVIEYEAR
GROUP BY m.STUDIONAME, s.STARNAME
HAVING COUNT (s.MOVIETITLE)>=ALL(
(SELECT COUNT(s2.MOVIETITLE) 
FROM STARSIN s2, MOVIE m2 
WHERE s2.MOVIEYEAR=m2.[YEAR] AND s2.MOVIETITLE=m2.TITLE
GROUP BY m2.STUDIONAME, s2.STARNAME))

--7 option 2
SELECT actor_movie_count.*
FROM (SELECT m.STUDIONAME, si.STARNAME, COUNT(si.MOVIETITLE) NUM_MOVIES
		FROM STARSIN si, MOVIE m
		WHERE m.TITLE = si.MOVIETITLE AND m.YEAR = si.MOVIEYEAR
		GROUP BY m.STUDIONAME, si.STARNAME) actor_movie_count
WHERE actor_movie_count.num_movies >= ALL(SELECT COUNT(si2.MOVIETITLE)
										FROM STARSIN si2, MOVIE m2
										WHERE m2.TITLE = si2.MOVIETITLE AND m2.YEAR = si2.MOVIEYEAR
										GROUP BY m2.STUDIONAME, si2.STARNAME);

--8
SELECT STARSIN.MOVIETITLE, STARSIN.MOVIEYEAR, COUNT(*) AS num_actors
FROM STARSIN
GROUP BY STARSIN.MOVIETITLE, STARSIN.MOVIEYEAR
HAVING COUNT(STARSIN.STARNAME)>2;