--1
SELECT DISTINCT STARSIN.STARNAME
FROM STARSIN , MOVIESTAR
WHERE STARSIN.STARNAME=MOVIESTAR.NAME AND STARSIN.MOVIETITLE='The Usual Suspects' AND MOVIESTAR.GENDER='M';

--2
SELECT DISTINCT STARSIN.STARNAME
FROM STARSIN, MOVIE
WHERE MOVIE.YEAR=1995 AND MOVIE.STUDIONAME='MGM' AND STARSIN.MOVIETITLE=MOVIE.TITLE;

--3
SELECT DISTINCT MOVIEEXEC.NAME
FROM MOVIEEXEC, STUDIO, MOVIE
WHERE MOVIE.STUDIONAME='MGM' AND MOVIE.PRODUCERC#=MOVIEEXEC.CERT#

--4
SELECT m1.TITLE
FROM MOVIE m1, MOVIE m2
WHERE m2.TITLE='Star Wars' AND m1.LENGTH>m2.LENGTH;

--5
SELECT e1.NAME
FROM MOVIEEXEC e1, MOVIEEXEC e2
WHERE e2.NAME='Stephen Spielberg' AND e1.NETWORTH>e2.NETWORTH;

--6
SELECT m1.TITLE
FROM MOVIE m1, MOVIEEXEC e1, MOVIEEXEC e2
WHERE e2.NAME='Stephen Spielberg' AND e1.NETWORTH>e2.NETWORTH AND m1.PRODUCERC#=e1.CERT#;