--1
SELECT s.NAME
FROM SHIPS s, CLASSES c
WHERE c.DISPLACEMENT>50000 AND s.CLASS=c.CLASS

--2
SELECT DISTINCT s.NAME, c.DISPLACEMENT, c.NUMGUNS
FROM CLASSES c, SHIPS s, BATTLES b, OUTCOMES o
WHERE o.BATTLE='Guadalcanal' AND o.SHIP=s.NAME AND s.CLASS=c.CLASS;

--3
SELECT c.COUNTRY
FROM CLASSES c
WHERE c.[TYPE]='bb'
INTERSECT
SELECT c.COUNTRY
FROM CLASSES c
WHERE c.[TYPE]='bc'

--4
SELECT s.NAME
FROM OUTCOMES o1, OUTCOMES o2, SHIPS s, BATTLES b1, BATTLES b2
WHERE o1.RESULT='damaged' AND o1.BATTLE=b1.NAME and o2.BATTLE=b2.NAME AND b2.[DATE]>b1.[DATE] AND o1.SHIP=s.NAME AND o2.SHIP=s.NAME;
