--1
SELECT MOVIE.TITLE, MOVIEEXEC.NAME
FROM MOVIEEXEC JOIN MOVIE ON MOVIEEXEC.CERT#=MOVIE.PRODUCERC#
WHERE MOVIE.PRODUCERC#=ANY(SELECT MOVIE.PRODUCERC# FROM MOVIE WHERE MOVIE.TITLE='Star Wars');

--2
SELECT DISTINCT MOVIEEXEC.NAME
FROM MOVIEEXEC JOIN MOVIE ON MOVIEEXEC.CERT#=MOVIE.PRODUCERC# AND MOVIE.TITLE IN (SELECT STARSIN.MOVIETITLE FROM STARSIN WHERE STARSIN.STARNAME='Harrison Ford');

--3
SELECT DISTINCT s.NAME, st.STARNAME
FROM STARSIN st, STUDIO s JOIN MOVIE m ON m.STUDIONAME=s.NAME
WHERE st.MOVIETITLE = m.TITLE AND st.MOVIEYEAR=m.[YEAR]
ORDER BY s.NAME

--4
SELECT DISTINCT st.STARNAME, mv.NETWORTH, m.TITLE
FROM MOVIEEXEC mv,  STARSIN st JOIN MOVIE m ON st.MOVIETITLE=m.TITLE AND st.MOVIEYEAR=m.[YEAR]
WHERE m.PRODUCERC# = mv.CERT# AND mv.CERT# = 
(SELECT MOVIEEXEC.CERT# FROM MOVIEEXEC WHERE MOVIEEXEC.NETWORTH = (SELECT MAX(MOVIEEXEC.NETWORTH) FROM MOVIEEXEC))
ORDER BY m.TITLE;

--5
SELECT ms.NAME, st.MOVIETITLE
FROM MOVIESTAR ms LEFT JOIN STARSIN st ON ms.NAME=st.STARNAME 
WHERE st.MOVIETITLE IS NULL
